name: fmlm_edit
backbone: dit_edit
parameterization: mean
time_conditioning: True
T: 0
causal_attention: False
t_max: 1.0
t_min: 0.0
double_temb: True
learnable_loss_weighting: False
use_instruction_conditioning: False
ignore_bos: False
upweight_changed_tokens: False
diagonal_fraction: 0.5
offdiagonal_sampling: uniform_diff
set_midpoint: midpoint
boundary_prob: 32
distillation_method: PSD
use_mse_loss_psd: False
rescale_offdiag_loss_psd: False
use_ema_for_psd_target: False
initialize_student_from_teacher: True
teacher_path: ''
